### PR TITLE
Removed vocabulary namespace restrictions and added new config option…

### PR DESCRIPTION
**Pull request by DarkGigaByte**
… for vocabulary namespaces on types

https://github.com/api-platform/schema-generator/issues/22

### CODE REVIEW

**Comment by dunglas** [comment]
Looks good!

Can you add a test using another vocabulary?

**Comment by DarkGigaByte** [comment]
Done!

**Comment by dunglas** [comment]
Thank you @DarkGigaByte

**Comment by dunglas** [comment]
It would be nice if you can also update the doc: https://github.com/api-platform/doc

**Pull request merged**
