### PR TITLE
Add support for entity operation annotations

### PR DESCRIPTION
**Pull request by toby-griffiths**
New version of PR #110 for changes rebased onto current master…

I've added the possibility to add the following to a type definition to support operation annotations…

    types:
        Person:
            operations:
                item:
                    <method>:
                        method: '<method>' # or…
                        router_name: '<route_name>'
                    # ...
                collection:
                    <method>:
                        method: '<method>' # or…
                        router_name: '<route_name>'
                    # ...

This will probably want documenting too, but not got time to do this right now.  I've made a reminder to do this if someone else doesn;t get to it before I do.

### CODE REVIEW

**Comment by dunglas** [comment]
First of all, sorry for the late reply. Could you rebase it please? It should fix the test.

**Comment by toby-griffiths** [comment]
@dunglas Done!

**Comment by dunglas** [comment]
There is a problem with the rebase isn't it?

**Comment by toby-griffiths** [comment]
I looked at the log & looks like style issues, which I've corrected.  Have I missed something else?

**Comment by dunglas** [comment]
The PR contains 35 commits, it looks weird

**Comment by toby-griffiths** [comment]
Hmmm… OK.  Perhaps it's easier if I start again.

**Pull request closed without merging**
