### PR TITLE
Added ability to create custom classes

### PR DESCRIPTION
**Pull request by ZeBigDuck**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | n/a
| License       | MIT
| Doc PR        | n/a

This PR allows to create custom classes.
If the class is not found on rdf provided, it will create the class anyway. The class will be supporting base types from the `guessFrom` parameter (`Thing` if none is given).

I did this because I'm currently creating a new schema, and this allows to generate custom entities and relations, making this tool more awesome :)

BTW, didn't find anymore the doc in the repo, I don't know where I should complete it.

Hope I'll succeed to keep this PR clean this time!

### CODE REVIEW

**Comment by ksom** [comment]
:+1: 
Thanks

**Comment by keyermann** [comment]
Hi,
When I use your PR with the api-platform tutorial schema.yml I have this error: 
```bash
[EasyRdf_Parser_Exception]           
Failed to parse statement on line 1
```

here is the schema.yml
```yaml
rdfa:
    # - https://raw.githubusercontent.com/schemaorg/schemaorg/sdo-gozer/data/schema.rdfa
    - https://raw.githubusercontent.com/schemaorg/schemaorg/sdo-deimos/data/schema.rdfa
annotationGenerators: # Generators we want to use, keep it as is for any API Platform project
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\PhpDocAnnotationGenerator
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\DoctrineOrmAnnotationGenerator
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\ConstraintAnnotationGenerator
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\DunglasApiAnnotationGenerator
debug: true
namespaces:
    entity: AppBundle\Entity # The default namespace for entities, following API Platform and Symfony best practices
types: # The list of type to generated (a PHP entity class by type will be generated)
    SocialMediaPosting: ~
    BlogPosting: ~ # A type to generate a PHP entity class from, including all its properties (here this type has no specific property, they are all inherited)
    Article: # Schema.org has an inheritance system, we will configure all types of the hierarchy
        properties: # The list of properties we want to use
            articleBody: ~
            articleSection: ~
    CreativeWork:
        properties:
            author:
                range: Person # PHP Schema handle relations. Here we force the type of the property to Person
                cardinality: (*..0) # Force the cardinality of the relation
            headline: ~
            isFamilyFriendly: ~
            datePublished: ~
    Thing:
        properties:
            name: ~
    Person: # Person is a relation of the "CreativeWork" type (property "author"), PHP Schema will generate relations for us
        properties: {} # We don't want any specific property for a person except "name" inherited from Thing
```

**Comment by sroze** [comment]
@ZeBigDuck Could you have a look at the issue reported by @keyermann?

**Comment by keyermann** [comment]
@ZeBigDuck @sroze 
My bad , apparently my corporate proxy was the problem. I do not know why...
But without proxy it works ! So great PR ! ;)

Thank you and sorry ;)

**Comment by ZeBigDuck** [comment]
No problem!

BTW, Is there something I could do to improve this PR to get it merged ?
Only @keyermann, @ksom and myself find this useful ? :(

In my opinion, this PR make this bundle really more usable.

**Comment by sroze** [comment]
You've got a :+1: from me (even if we need to refactor the `TypesGenerator` class :wink:).

**Comment by keyermann** [comment]
:+1:  from all the IGN.fr geodetic developer team here :wink:

**Comment by dunglas** [comment]
Thank you very much @ZeBigDuck!

**Comment by ZeBigDuck** [comment]
Yeah! Thank you everybody :) Feel famous \o_

Thank you @dunglas for merging!

**Comment by keyermann** [comment]
Hi @ZeBigDuck 

I have a little problem again... Your PR work properly but I have some misunderstanding with NelmioApiDocBundle.

If I configure two resources with the same guessFrom, NelmioApiDocBundle will group them in the same section with the name of the first one...

exemple: 
```yaml
    [...]
    Site:
        parent: false
        guessFrom: Place
    Station:
        parent: false
        guessFrom: Place
```

site_station

Do you have any idea on the way to fix that ?
Thanks!

**Comment by ZeBigDuck** [comment]
I **think** this is relative to the annotation set in the entity :
 * @Iri("http://schema.org/Place")

I think the api doc uses these annotations, and as there is no rdfa for your own entity, I think it's necessary to redefine the way nelmioApiDoc generates the doc. (I think it remains to apiPlatform to be changed).

I have no time for this right now, but when I'll have, I'll try to provide a fix.

**Pull request merged**
