### PR TITLE
Add embeddable support

### PR DESCRIPTION
**Pull request by JhonnyL**
| Q             | A
| ------------- | ---
| Bug fix?	| no
| New Feature?	| yes
| BC Breaks?	| no
| Deprecations?	| no
| Tests pass?	| yes
| Fixed tickets	| n/a

### CODE REVIEW

**Comment by sroze** [comment]
LGTM :+1:

**Comment by rande** [comment]
@dunglas Can you review this PR ? seems to be ok from here ;)

**Comment by dunglas** [comment]
Thank you @JhonnyL! Can you update the doc accordingly? https://github.com/api-platform/doc

**Comment by JhonnyL** [comment]
@dunglas Thanks, will do.

**Comment by teohhanhui** [comment]
Question: Does this work with the API Bundle currently (how?), or do I have to handle it manually in the normalizer?

**Comment by dunglas** [comment]
AFAIK this is not supported but support for that would be nice.

**Comment by teohhanhui** [comment]
I'll see if I can come up with something, since I need this anyway. At least a guide on how to set up such a (reusable) normalizer for embedded (pseudo-)resources.

**Comment by teohhanhui** [comment]
@dunglas I've got the normalization part working but denormalization is tripping me up here:

https://github.com/dunglas/DunglasApiBundle/blob/57ba9e8ccf424de0e800d35785375c1939008ec5/JsonLd/Serializer/ItemNormalizer.php#L370-L377

Why is that check necessary? It seems to be already handled here:

https://github.com/dunglas/DunglasApiBundle/blob/57ba9e8ccf424de0e800d35785375c1939008ec5/JsonLd/Serializer/ItemNormalizer.php#L196

**Comment by teohhanhui** [comment]
What I've got so far:

https://gist.github.com/teohhanhui/f40ac033ed3c09b1bf83

**Comment by teohhanhui** [comment]
I've worked around the problem by filtering the embedded property out from the data passed to `ItemNormalizer` (using a custom normalizer for the parent resource, which delegates to `ItemNormalizer` by composition).

**Comment by nicolasricci** [comment]
great work @teohhanhui. i am currently working on embedded resources so it will save me some time.
@dunglas any chance to include the `AbstractEmbeddedResourceNormalizer` in the api-bundle if we can provide some tests & documentation?

**Comment by dunglas** [comment]
Yes, as soon as it is tested and document :+1:

**Comment by teohhanhui** [comment]
@nicolasricci This is only meant as a hack / workaround... But if you want to take it from there, please feel free.

**Comment by teohhanhui** [comment]
Personally I'd prefer if we are able to fix `ItemNormalizer` to not falsely advertise its capability to normalize / denormalize certain things.

https://github.com/dunglas/DunglasApiBundle/issues/166#issuecomment-124310685
https://github.com/dunglas/DunglasApiBundle/issues/166#issuecomment-160087339

**Comment by nicolasricci** [comment]
@teohhanhui i see your point... I will see if there is any clean way to patch the `ItemNormalizer` then. If not I will keep your workaround until we can do better.

**Pull request merged**
